"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {getAccountantDashboard,getPilotReport,hasSession,pilotTemplateUrl,savePilotMetric,type AccountantWorkspace,type PilotReport} from "@/lib/api";

const checks=["ledger_export","bank_statement","opening_balance","closing_balance","currency_confirmed","prior_close_time"];
export default function PilotPage(){
 const [clients,setClients]=useState<AccountantWorkspace[]>([]),[workspaceId,setWorkspaceId]=useState(0),[report,setReport]=useState<PilotReport|null>(null),[message,setMessage]=useState("");
 const [form,setForm]=useState({period:new Date().toISOString().slice(0,7),setup_minutes:"",manual_close_minutes:"",ledgerly_close_minutes:"",matched_count:"0",possible_count:"0",unmatched_count:"0",validation_failures:"0",corrections_required:"0",report_completed:false,repeated_monthly_usage:false,feedback:"",testimonial_permission:false,readiness_checklist:Object.fromEntries(checks.map(k=>[k,false])) as Record<string,boolean>});
 useEffect(()=>{if(!hasSession()){location.href="/login";return}getAccountantDashboard().then(x=>{setClients(x.clients);if(x.clients[0])setWorkspaceId(x.clients[0].id)}).catch(e=>setMessage(e instanceof Error?e.message:"Unable to load pilots."))},[]);
 useEffect(()=>{if(workspaceId)getPilotReport(workspaceId).then(setReport).catch(e=>setMessage(e instanceof Error?e.message:"Unable to load pilot report."))},[workspaceId]);
 async function submit(e:React.FormEvent){e.preventDefault();if(!workspaceId)return;const number=(v:string)=>v===""?null:Number(v);try{await savePilotMetric(workspaceId,form.period,{setup_minutes:number(form.setup_minutes),manual_close_minutes:number(form.manual_close_minutes),ledgerly_close_minutes:number(form.ledgerly_close_minutes),matched_count:Number(form.matched_count),possible_count:Number(form.possible_count),unmatched_count:Number(form.unmatched_count),validation_failures:Number(form.validation_failures),corrections_required:Number(form.corrections_required),report_completed:form.report_completed,repeated_monthly_usage:form.repeated_monthly_usage,feedback:form.feedback,testimonial_permission:form.testimonial_permission,readiness_checklist:form.readiness_checklist});setReport(await getPilotReport(workspaceId));setMessage("Pilot evidence saved.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to save pilot evidence.")}}
 return <main className="studio-shell"><header className="studio-header"><Link href="/accountant">←</Link><div><span>PILOT READINESS</span><h1>Measured close, no invented results</h1><p>Capture readiness, elapsed time, reconciliation outcomes, exceptions and consent per client month.</p></div></header>{message&&<div className="studio-error" role="status">{message}</div>}<div className="studio-grid"><form className="studio-card" onSubmit={submit}><h2>Guided pilot record</h2><label>Workspace<select value={workspaceId} onChange={e=>setWorkspaceId(Number(e.target.value))}>{clients.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Period<input type="month" value={form.period} onChange={e=>setForm({...form,period:e.target.value})}/></label><fieldset><legend>Data readiness</legend>{checks.map(key=><label className="file-choice" key={key}><input type="checkbox" checked={form.readiness_checklist[key]} onChange={e=>setForm({...form,readiness_checklist:{...form.readiness_checklist,[key]:e.target.checked}})}/><span>{key.replaceAll("_"," ")}</span></label>)}</fieldset>{["setup_minutes","manual_close_minutes","ledgerly_close_minutes","matched_count","possible_count","unmatched_count","validation_failures","corrections_required"].map(key=><label key={key}>{key.replaceAll("_"," ")}<input type="number" min="0" value={form[key as keyof typeof form] as string} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>Feedback<input value={form.feedback} onChange={e=>setForm({...form,feedback:e.target.value})}/></label>{["report_completed","repeated_monthly_usage","testimonial_permission"].map(key=><label className="file-choice" key={key}><input type="checkbox" checked={form[key as keyof typeof form] as boolean} onChange={e=>setForm({...form,[key]:e.target.checked})}/><span>{key.replaceAll("_"," ")}</span></label>)}<button className="primary-action">Save pilot evidence</button><a className="secondary-action" href={pilotTemplateUrl()} download>Download sample template</a></form><section className="studio-card"><h2>Exportable pilot result</h2><p>{report?.notice}</p>{report?.periods.map(x=><article className="run-row" key={x.period}><div><strong>{x.period}</strong><small>Time saved: {x.time_saved_minutes??"unknown"} min · Reconciliation accuracy: {x.reconciliation_accuracy_percent??"unknown"}%</small></div><span className={`status-pill ${x.report_completed?"":"blocked"}`}>{x.report_completed?"report complete":"incomplete"}</span><p>{x.validation_failures} validation failures · {x.corrections_required} corrections · {x.matched_count}/{x.possible_count}/{x.unmatched_count} matched/possible/unmatched</p></article>)}</section></div></main>
}
