"use client";
import { useEffect, useState } from "react";
import { ArrowLeft, Download, FileText, Link2 } from "lucide-react";
import Link from "next/link";
import { createReport, createReportShare, createReportTemplate, downloadReport, getLatestFinancials, hasSession, listReportTemplates, type FinancialCalculation, type ReportSnapshot, type ReportTemplate } from "@/lib/api";

const languages=[['en','English'],['bn','বাংলা'],['ar','العربية'],['hi','हिन्दी'],['es','Español']] as const;
export default function ReportsPage(){const [templates,setTemplates]=useState<ReportTemplate[]>([]),[financials,setFinancials]=useState<FinancialCalculation|null>(null),[report,setReport]=useState<ReportSnapshot|null>(null),[title,setTitle]=useState("Monthly financial report"),[business,setBusiness]=useState("My business"),[language,setLanguage]=useState<ReportTemplate['language']>('en'),[brand,setBrand]=useState('#7357FF'),[busy,setBusy]=useState(false),[error,setError]=useState(""),[share,setShare]=useState("");
async function load(){try{const [t,f]=await Promise.all([listReportTemplates(),getLatestFinancials()]);setTemplates(t);setFinancials(f)}catch(e){setError(e instanceof Error?e.message:"Unable to load Report Studio.")}}useEffect(()=>{if(!hasSession()){location.href='/login';return}void Promise.resolve().then(load)},[]);
async function generate(){if(!financials)return;setBusy(true);setError("");try{const template=await createReportTemplate({title,business_name:business,language,brand_color:brand,sections:['executive_summary','profit_loss','cash_flow','receivables_payables','risks','notes'],selected_kpis:['revenue','gross_profit','net_profit','gross_margin','net_margin','closing_cash','receivables','payables']});setTemplates(old=>[...old,template]);setReport(await createReport({template_id:template.id,calculation_id:financials.id,period:financials.periods.at(-1)?.key??new Date().toISOString().slice(0,7)}))}catch(e){setError(e instanceof Error?e.message:"Report generation failed.")}finally{setBusy(false)}}
  return <main className="studio-shell" dir={language==='ar'?'rtl':'ltr'}><header className="studio-header"><Link href="/" aria-label="Back to dashboard"><ArrowLeft size={18}/></Link><div><span>LEDGERLY REPORTING</span><h1>Report Studio</h1><p>Build reusable, validated reports without changing source currency or numbers.</p></div></header>{error&&<div className="studio-error" role="alert">{error}<button onClick={load}>Retry</button></div>}<div className="studio-grid"><section className="studio-card"><h2>Report template</h2><label>Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Client / business name<input value={business} onChange={e=>setBusiness(e.target.value)}/></label><label>Brand colour<input type="color" value={brand} onChange={e=>setBrand(e.target.value)}/></label><label>Language<select value={language} onChange={e=>setLanguage(e.target.value as ReportTemplate['language'])}>{languages.map(([code,name])=><option key={code} value={code}>{name}</option>)}</select></label><button className="primary-action" onClick={generate} disabled={busy||!financials}><FileText size={16}/>{busy?'Generating…':'Generate validated report'}</button><p className="reuse-note">{templates.length} reusable template{templates.length===1?'':'s'} saved for future months.</p></section><section className="studio-card report-preview"><h2>Preview</h2>{report?<><div style={{borderTop:`5px solid ${report.brand_color}`}}><small>{report.period}</small><h3>{report.title}</h3><p>{report.business_name}</p>{report.metrics.map(m=><div className="preview-metric" key={m.id}><span>{m.key.replaceAll('_',' ')}</span><strong>{m.value?.toLocaleString()??'—'}</strong><small>{m.evidence_ref}</small></div>)}</div><div className="export-actions"><button onClick={()=>downloadReport(report.id,'pdf')}><Download size={14}/>PDF</button><button onClick={()=>downloadReport(report.id,'xlsx')}><Download size={14}/>Excel</button><button onClick={async()=>{const result=await createReportShare(report.id);setShare(`${location.origin.replace(':3000',':8000')}${result.url}`)}}><Link2 size={14}/>Secure link</button></div>{share&&<output className="share-output">Expires automatically: <a href={share}>{share}</a></output>}</>:<p className="empty-copy">Choose template details to generate a report from the latest validated calculation.</p>}</section></div></main>}
