CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL UNIQUE,
    full_name VARCHAR(120) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

-- ledgerly:statement-break

CREATE INDEX IF NOT EXISTS ix_users_email ON users (email);

-- ledgerly:statement-break

CREATE TABLE IF NOT EXISTS uploads (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    filename VARCHAR(255) NOT NULL,
    file_type VARCHAR(20) NOT NULL,
    checksum VARCHAR(64) NOT NULL,
    row_count INTEGER NOT NULL DEFAULT 0,
    confidence DOUBLE PRECISION NOT NULL DEFAULT 0,
    normalized_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL
);

-- ledgerly:statement-break

CREATE INDEX IF NOT EXISTS ix_uploads_user_id ON uploads (user_id);

-- ledgerly:statement-break

CREATE INDEX IF NOT EXISTS ix_uploads_checksum ON uploads (checksum);

-- ledgerly:statement-break

CREATE INDEX IF NOT EXISTS ix_uploads_created_at ON uploads (created_at);

-- ledgerly:statement-break

CREATE TABLE IF NOT EXISTS pulses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_id INTEGER NOT NULL UNIQUE REFERENCES uploads(id) ON DELETE CASCADE,
    score INTEGER NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    summary TEXT NOT NULL,
    factors JSONB NOT NULL DEFAULT '[]'::jsonb,
    metrics JSONB NOT NULL DEFAULT '{}'::jsonb
);
