ALTER TABLE reconciliation_runs ADD COLUMN opening_balance DOUBLE PRECISION;
-- ledgerly:statement-break
ALTER TABLE reconciliation_runs ADD COLUMN closing_balance DOUBLE PRECISION;
-- ledgerly:statement-break
ALTER TABLE reconciliation_runs ADD COLUMN completed_at TIMESTAMPTZ;
-- ledgerly:statement-break
ALTER TABLE reconciliation_matches ALTER COLUMN status SET DEFAULT 'pending';
-- ledgerly:statement-break
ALTER TABLE reconciliation_matches ADD COLUMN exception_type VARCHAR(40);
-- ledgerly:statement-break
ALTER TABLE reconciliation_matches ADD COLUMN exception_status VARCHAR(20);
-- ledgerly:statement-break
ALTER TABLE reconciliation_matches ADD COLUMN review_note TEXT;
-- ledgerly:statement-break
ALTER TABLE reconciliation_matches ADD COLUMN original_state JSONB NOT NULL DEFAULT '{}'::jsonb;
-- ledgerly:statement-break
ALTER TABLE reconciliation_matches ADD COLUMN suggested_state JSONB NOT NULL DEFAULT '{}'::jsonb;
-- ledgerly:statement-break
ALTER TABLE reconciliation_matches ADD COLUMN final_state JSONB;
-- ledgerly:statement-break
ALTER TABLE reconciliation_matches ADD COLUMN reviewed_at TIMESTAMPTZ;
-- ledgerly:statement-break
CREATE INDEX ix_reconciliation_matches_status ON reconciliation_matches(status);
-- ledgerly:statement-break
CREATE INDEX ix_reconciliation_matches_exception_type ON reconciliation_matches(exception_type);
-- ledgerly:statement-break
CREATE INDEX ix_reconciliation_matches_exception_status ON reconciliation_matches(exception_status);
-- ledgerly:statement-break
CREATE TABLE reconciliation_audit_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id INTEGER NOT NULL REFERENCES reconciliation_runs(id) ON DELETE CASCADE,
  match_id INTEGER REFERENCES reconciliation_matches(id) ON DELETE SET NULL,
  actor_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  action VARCHAR(40) NOT NULL,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  idempotency_key VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL
);
-- ledgerly:statement-break
CREATE INDEX ix_reconciliation_audit_events_run_id ON reconciliation_audit_events(run_id);
-- ledgerly:statement-break
CREATE INDEX ix_reconciliation_audit_events_match_id ON reconciliation_audit_events(match_id);
-- ledgerly:statement-break
CREATE INDEX ix_reconciliation_audit_events_actor_user_id ON reconciliation_audit_events(actor_user_id);
-- ledgerly:statement-break
CREATE INDEX ix_reconciliation_audit_events_action ON reconciliation_audit_events(action);
-- ledgerly:statement-break
CREATE UNIQUE INDEX uq_reconciliation_audit_idempotency ON reconciliation_audit_events(run_id, actor_user_id, idempotency_key) WHERE idempotency_key IS NOT NULL;
