CREATE TABLE workspace_closing_settings (user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, source_mappings JSONB NOT NULL DEFAULT '{}'::jsonb, customer_aliases JSONB NOT NULL DEFAULT '{}'::jsonb, vendor_aliases JSONB NOT NULL DEFAULT '{}'::jsonb, categories JSONB NOT NULL DEFAULT '{}'::jsonb, bank_rules JSONB NOT NULL DEFAULT '[]'::jsonb, fiscal_period JSONB NOT NULL DEFAULT '{}'::jsonb, calculation_preferences JSONB NOT NULL DEFAULT '{}'::jsonb, approval_preferences JSONB NOT NULL DEFAULT '{}'::jsonb, selected_report_template_id INTEGER, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
-- ledgerly:statement-break
CREATE TABLE monthly_closing_runs (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, period VARCHAR(20) NOT NULL, upload_ids JSONB NOT NULL DEFAULT '[]'::jsonb, calculation_id INTEGER REFERENCES calculation_versions(id) ON DELETE SET NULL, reconciliation_run_id INTEGER REFERENCES reconciliation_runs(id) ON DELETE SET NULL, idempotency_key VARCHAR(100) NOT NULL, status VARCHAR(20) NOT NULL, progress JSONB NOT NULL DEFAULT '{}'::jsonb, rules_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb, exceptions JSONB NOT NULL DEFAULT '[]'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at TIMESTAMPTZ, CONSTRAINT uq_monthly_closing_idempotency UNIQUE(user_id,idempotency_key));
CREATE INDEX ix_monthly_closing_runs_user_id ON monthly_closing_runs(user_id); CREATE INDEX ix_monthly_closing_runs_period ON monthly_closing_runs(period);
-- ledgerly:statement-break
CREATE TABLE monthly_closing_audit_events (id SERIAL PRIMARY KEY, run_id INTEGER NOT NULL REFERENCES monthly_closing_runs(id) ON DELETE CASCADE, actor_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, action VARCHAR(40) NOT NULL, details JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
-- ledgerly:statement-break
CREATE TABLE report_templates (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, title VARCHAR(160) NOT NULL, business_name VARCHAR(160) NOT NULL, logo_data TEXT, brand_color VARCHAR(12) NOT NULL DEFAULT '#7357FF', language VARCHAR(8) NOT NULL DEFAULT 'en', sections JSONB NOT NULL DEFAULT '[]'::jsonb, selected_kpis JSONB NOT NULL DEFAULT '[]'::jsonb, selected_charts JSONB NOT NULL DEFAULT '[]'::jsonb, notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX ix_report_templates_user_id ON report_templates(user_id);
-- ledgerly:statement-break
CREATE TABLE report_snapshots (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, template_id INTEGER NOT NULL REFERENCES report_templates(id) ON DELETE CASCADE, calculation_id INTEGER NOT NULL REFERENCES calculation_versions(id) ON DELETE CASCADE, period VARCHAR(20) NOT NULL, content JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
-- ledgerly:statement-break
CREATE TABLE report_shares (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, report_id INTEGER NOT NULL REFERENCES report_snapshots(id) ON DELETE CASCADE, token_hash VARCHAR(64) NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX ix_report_shares_token_hash ON report_shares(token_hash);
