-- Ledgerly Snowflake bootstrap
-- Run as a role allowed to create warehouses, databases, and schemas.

CREATE WAREHOUSE IF NOT EXISTS LEDGERLY_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS LEDGERLY;
CREATE SCHEMA IF NOT EXISTS LEDGERLY.BUSINESS;

USE WAREHOUSE LEDGERLY_WH;
USE DATABASE LEDGERLY;
USE SCHEMA BUSINESS;

CREATE SEQUENCE IF NOT EXISTS LEDGERLY_UPLOAD_SEQUENCE START = 1 INCREMENT = 1;

CREATE TABLE IF NOT EXISTS UPLOADS (
  UPLOAD_ID NUMBER NOT NULL DEFAULT LEDGERLY_UPLOAD_SEQUENCE.NEXTVAL,
  USER_ID NUMBER NOT NULL,
  FILENAME VARCHAR(255) NOT NULL,
  FILE_TYPE VARCHAR(20) NOT NULL,
  CHECKSUM VARCHAR(64) NOT NULL,
  ROW_COUNT NUMBER NOT NULL,
  CONFIDENCE FLOAT NOT NULL,
  NORMALIZED_DATA VARIANT NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_UPLOADS PRIMARY KEY (UPLOAD_ID)
);

CREATE TABLE IF NOT EXISTS BUSINESS_METRICS (
  UPLOAD_ID NUMBER NOT NULL,
  USER_ID NUMBER NOT NULL,
  METRIC_NAME VARCHAR(100) NOT NULL,
  METRIC_VALUE FLOAT NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT FK_BUSINESS_METRICS_UPLOAD
    FOREIGN KEY (UPLOAD_ID) REFERENCES UPLOADS (UPLOAD_ID)
);

CREATE TABLE IF NOT EXISTS PULSE_HISTORY (
  PULSE_ID VARCHAR(36) NOT NULL,
  UPLOAD_ID NUMBER NOT NULL,
  USER_ID NUMBER NOT NULL,
  SCORE NUMBER NOT NULL,
  CONFIDENCE FLOAT NOT NULL,
  SUMMARY VARCHAR(2000) NOT NULL,
  FACTORS VARIANT NOT NULL,
  METRICS VARIANT NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_PULSE_HISTORY PRIMARY KEY (PULSE_ID),
  CONSTRAINT FK_PULSE_HISTORY_UPLOAD
    FOREIGN KEY (UPLOAD_ID) REFERENCES UPLOADS (UPLOAD_ID)
);

CREATE ROLE IF NOT EXISTS LEDGERLY_APP_ROLE;
GRANT USAGE ON WAREHOUSE LEDGERLY_WH TO ROLE LEDGERLY_APP_ROLE;
GRANT USAGE ON DATABASE LEDGERLY TO ROLE LEDGERLY_APP_ROLE;
GRANT USAGE ON SCHEMA LEDGERLY.BUSINESS TO ROLE LEDGERLY_APP_ROLE;
GRANT USAGE ON SEQUENCE LEDGERLY.BUSINESS.LEDGERLY_UPLOAD_SEQUENCE
  TO ROLE LEDGERLY_APP_ROLE;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA LEDGERLY.BUSINESS
  TO ROLE LEDGERLY_APP_ROLE;
