USE WAREHOUSE LEDGERLY_WH;
USE DATABASE LEDGERLY;
USE SCHEMA BUSINESS;

SELECT CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();

SHOW TABLES LIKE 'UPLOADS';
SHOW TABLES LIKE 'BUSINESS_METRICS';
SHOW TABLES LIKE 'PULSE_HISTORY';

SELECT 'UPLOADS' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT FROM UPLOADS
UNION ALL
SELECT 'BUSINESS_METRICS', COUNT(*) FROM BUSINESS_METRICS
UNION ALL
SELECT 'PULSE_HISTORY', COUNT(*) FROM PULSE_HISTORY;

SELECT
  U.USER_ID,
  U.UPLOAD_ID,
  U.FILENAME,
  U.ROW_COUNT,
  COUNT(DISTINCT M.METRIC_NAME) AS DETECTED_METRICS,
  MAX(P.SCORE) AS BUSINESS_PULSE,
  MAX(U.CREATED_AT) AS UPLOADED_AT
FROM UPLOADS U
LEFT JOIN BUSINESS_METRICS M
  ON M.USER_ID = U.USER_ID AND M.UPLOAD_ID = U.UPLOAD_ID
LEFT JOIN PULSE_HISTORY P
  ON P.USER_ID = U.USER_ID AND P.UPLOAD_ID = U.UPLOAD_ID
GROUP BY U.USER_ID, U.UPLOAD_ID, U.FILENAME, U.ROW_COUNT
ORDER BY UPLOADED_AT DESC;
