"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CheckCircle2, LockKeyhole, Play, RefreshCw } from "lucide-react";
import Link from "next/link";
import { getClosingSettings, hasSession, listClosingRuns, listUploads, reopenClosingRun, runMonthlyClosing, saveClosingSettings, type ClosingRun, type ClosingSettings, type UploadRecord } from "@/lib/api";

export default function ClosingPage() {
  const [uploads,setUploads]=useState<UploadRecord[]>([]), [runs,setRuns]=useState<ClosingRun[]>([]), [settings,setSettings]=useState<ClosingSettings|null>(null);
  const [period,setPeriod]=useState(new Date().toISOString().slice(0,7)), [selected,setSelected]=useState<number[]>([]), [busy,setBusy]=useState(false), [error,setError]=useState("");
  const previousRules=useMemo(()=>runs[0]?.rules_snapshot,[runs]);
  async function load(){try{const [files,history,prefs]=await Promise.all([listUploads(),listClosingRuns(),getClosingSettings()]);setUploads(files);setRuns(history);setSettings(prefs)}catch(e){setError(e instanceof Error?e.message:"Unable to load monthly closing.")}}
  useEffect(()=>{if(!hasSession()){location.href="/login";return}void Promise.resolve().then(load)},[]);
  async function run(){if(!selected.length)return;setBusy(true);setError("");try{await runMonthlyClosing(period,selected,crypto.randomUUID());await load()}catch(e){setError(e instanceof Error?e.message:"Closing failed.")}finally{setBusy(false)}}
  async function save(){if(!settings)return;setBusy(true);try{await saveClosingSettings(settings);await load()}catch(e){setError(e instanceof Error?e.message:"Could not save preferences.")}finally{setBusy(false)}}
  return <main className="studio-shell"><header className="studio-header"><Link href="/" aria-label="Back to dashboard"><ArrowLeft size={18}/></Link><div><span>LEDGERLY WORKFLOW</span><h1>Monthly closing</h1><p>Reuse approved rules and run a controlled Clean → Reconcile → Calculate → Validate close.</p></div></header>
    {error&&<div className="studio-error" role="alert">{error}<button onClick={load}>Retry</button></div>}
    <div className="studio-grid"><section className="studio-card"><h2>Run Monthly Closing</h2><label>Report period<input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></label><fieldset><legend>Select source files</legend>{uploads.length?uploads.map(file=><label className="file-choice" key={file.id}><input type="checkbox" checked={selected.includes(file.id)} onChange={()=>setSelected(ids=>ids.includes(file.id)?ids.filter(id=>id!==file.id):[...ids,file.id])}/><span>{file.filename}<small>{file.row_count} rows</small></span></label>):<p className="empty-copy">Upload source files from the dashboard first.</p>}</fieldset><button className="primary-action" disabled={busy||!selected.length} onClick={run}>{busy?<RefreshCw className="spin" size={16}/>:<Play size={16}/>}Run Monthly Closing</button><small className="reuse-note"><CheckCircle2 size={13}/> Approved mappings, aliases, categories and bank rules will be reused{previousRules?" from the previous run":""}.</small></section>
    <section className="studio-card"><h2>Saved workflow preferences</h2><p>These settings stay isolated to this workspace and carry forward next month.</p><label>Fiscal year starts in month<input type="number" min="1" max="12" value={String(settings?.fiscal_period.year_start??1)} onChange={e=>settings&&setSettings({...settings,fiscal_period:{...settings.fiscal_period,year_start:Number(e.target.value)}})}/></label><label>Approval mode<select value={String(settings?.approval_preferences.mode??"review_exceptions")} onChange={e=>settings&&setSettings({...settings,approval_preferences:{...settings.approval_preferences,mode:e.target.value}})}><option value="review_exceptions">Review exceptions</option><option value="manual">Manual approval</option></select></label><button className="secondary-action" disabled={!settings||busy} onClick={save}>Save preferences</button></section></div>
    <section className="studio-card history"><h2>Run history</h2>{runs.length?runs.map(run=><article className="run-row" key={run.id}><div><strong>{run.period}</strong><span className={`status-pill ${run.status}`}>{run.status}</span><small>{Object.entries(run.progress).map(([step,state])=>`${step}: ${state}`).join(" · ")}</small></div><div><span>{run.exceptions.length} exceptions</span>{run.status==="completed"&&<button onClick={async()=>{await reopenClosingRun(run.id);await load()}}>Reopen</button>}</div>{run.status==="blocked"&&<p><LockKeyhole size={14}/> Completion is prevented until blocking validations are resolved.</p>}</article>):<p className="empty-copy">No monthly closing runs yet.</p>}</section></main>
}
