"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, CircleAlert, RefreshCw, Search, ShieldCheck } from "lucide-react";
import { ApiError, createReconciliation, getReconciliation, hasSession, listReconciliations, listUploads, manualReconciliationMatch, reconciliationAction, reviewReconciliationMatch, type Reconciliation, type ReconciliationMatch, unmatchReconciliation, updateReconciliationBalance } from "@/lib/api";

const tabs = ["exact", "possible", "unmatched", "exceptions"] as const;
const label = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, c => c.toUpperCase());
const money = (value: number | null) => value == null ? "—" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value);

export default function ReconciliationCenter() {
  const [run, setRun] = useState<Reconciliation | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [tab, setTab] = useState<(typeof tabs)[number]>("exact"), [query, setQuery] = useState(""), [statusFilter, setStatusFilter] = useState("all"), [sort, setSort] = useState("date");
  const [selected, setSelected] = useState<ReconciliationMatch | null>(null), [busy, setBusy] = useState(false), [note, setNote] = useState("");
  const [opening, setOpening] = useState(""), [closing, setClosing] = useState(""), [uploads, setUploads] = useState<Array<{id:number;filename:string}>>([]), [bank, setBank] = useState(""), [ledger, setLedger] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const runs = await listReconciliations(); if (runs[0]) setRun(await getReconciliation(runs[0].id)); setUploads(await listUploads()); } catch (e) { setError(e instanceof ApiError ? e.message : "Could not load reconciliation."); } finally { setLoading(false); } };
  useEffect(() => { if (!hasSession()) { window.location.href = "/login"; return; } void (async () => { try { const runs = await listReconciliations(); if (runs[0]) setRun(await getReconciliation(runs[0].id)); setUploads(await listUploads()); } catch (e) { setError(e instanceof ApiError ? e.message : "Could not load reconciliation."); } finally { setLoading(false); } })(); }, []);
  const items = useMemo(() => (run?.matches ?? []).filter(m => tab === "exceptions" ? Boolean(m.exception_type) : m.match_type === tab).filter(m => statusFilter === "all" || m.status === statusFilter).filter(m => `${m.transaction_date} ${m.amount} ${m.rule} ${m.exception_type}`.toLowerCase().includes(query.toLowerCase())).sort((a,b) => sort === "amount" ? (b.amount ?? 0)-(a.amount ?? 0) : String(a.transaction_date).localeCompare(String(b.transaction_date))), [run, tab, statusFilter, query, sort]);
  const mutate = async (work: () => Promise<unknown>) => { if (!run) return; setBusy(true); setError(""); try { await work(); setRun(await getReconciliation(run.id)); setSelected(null); setNote(""); } catch(e) { setError(e instanceof ApiError ? e.message : "Action failed. Please retry."); } finally { setBusy(false); } };
  const create = async () => { setBusy(true); try { setRun(await createReconciliation(Number(bank), Number(ledger))); } catch(e) { setError(e instanceof ApiError ? e.message : "Could not create reconciliation."); } finally { setBusy(false); } };
  if (loading) return <main className="recon-state"><span className="loading-spinner"/><h1>Loading Reconciliation Center</h1></main>;
  if (!run) return <main className="recon-state"><ShieldCheck size={42}/><h1>Start a reconciliation</h1><p>Choose a bank statement and ledger upload. Ledgerly keeps both source files unchanged.</p>{error && <div className="recon-error">{error}</div>}<div className="recon-create"><select aria-label="Bank statement" value={bank} onChange={e=>setBank(e.target.value)}><option value="">Bank statement</option>{uploads.map(u=><option key={u.id} value={u.id}>{u.filename}</option>)}</select><select aria-label="Ledger" value={ledger} onChange={e=>setLedger(e.target.value)}><option value="">Ledger</option>{uploads.map(u=><option key={u.id} value={u.id}>{u.filename}</option>)}</select><button disabled={!bank||!ledger||bank===ledger||busy} onClick={create}>Create reconciliation</button></div><Link href="/">Back to overview</Link></main>;
  const readonly = run.status === "completed";
  return <div className="recon-shell"><header className="recon-top"><Link href="/" aria-label="Back to overview"><ArrowLeft size={18}/></Link><div><span>Ledgerly</span><strong>Reconciliation Center</strong></div><span className={`run-status ${readonly?"done":""}`}>{readonly?"Completed":"In review"}</span></header><main className="recon-page">
    <section className="recon-heading"><div><p>FINANCIAL CONTROL</p><h1>Reconciliation #{run.id}</h1><span>Review deterministic matches and resolve possible exceptions without changing source records.</span></div><div className="completion"><strong>{run.completion_percent}%</strong><span>reviewed</span></div></section>
    {error && <div className="recon-error" role="alert">{error}<button onClick={load}>Retry</button></div>}
    <section className="recon-summary">{["exact","possible","unmatched","exceptions","approved"].map(k=><div key={k}><span>{label(k)}</span><strong>{run.counts[k]??0}</strong></div>)}</section>
    <section className="balance-card"><div><h2>Balance validation</h2><p>Statement movement must agree with ledger movement before completion.</p></div><label>Opening balance<input type="number" value={opening} placeholder={String(run.balance.opening_balance??"")} disabled={readonly} onChange={e=>setOpening(e.target.value)}/></label><label>Closing balance<input type="number" value={closing} placeholder={String(run.balance.closing_balance??"")} disabled={readonly} onChange={e=>setClosing(e.target.value)}/></label><div><span>Ledger movement</span><strong>{money(run.balance.calculated_movement)}</strong></div><div><span>Unresolved difference</span><strong className={run.balance.passed?"pass":"fail"}>{money(run.balance.variance)}</strong></div><button disabled={readonly||opening===""||closing===""||busy} onClick={()=>mutate(()=>updateReconciliationBalance(run.id,Number(opening),Number(closing)))}>Validate</button></section>
    <section className="review-card"><div className="review-toolbar"><div className="recon-tabs" role="tablist">{tabs.map(t=><button role="tab" aria-selected={tab===t} className={tab===t?"active":""} key={t} onClick={()=>setTab(t)}>{label(t)} <b>{t==="exceptions"?run.counts.exceptions:run.counts[t]??0}</b></button>)}</div><button className="bulk" disabled={readonly||busy} onClick={()=>mutate(()=>reconciliationAction(run.id,"bulk-approve-exact"))}><Check size={14}/>Approve safe exact</button></div><div className="filters"><label><Search size={14}/><input aria-label="Search transactions" placeholder="Search date, amount, evidence…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">All statuses</option><option>pending</option><option>approved</option><option>rejected</option><option>manual</option></select><select aria-label="Sort transactions" value={sort} onChange={e=>setSort(e.target.value)}><option value="date">Date</option><option value="amount">Amount</option></select></div>
    <div className="match-list">{items.length===0?<div className="empty">No transactions match these filters.</div>:items.map(m=><button className="match-row" key={m.id} onClick={()=>{setSelected(m);setNote(m.review_note??"")}}><span className={`match-icon ${m.exception_type?"warn":""}`}>{m.exception_type?<CircleAlert size={15}/>:<Check size={15}/>}</span><span><strong>{m.transaction_date??"No date"}</strong><small>{m.rule}</small></span><span>{m.exception_type?`Possible ${label(m.exception_type)}`:label(m.match_type)}</span><strong>{money(m.amount)}</strong><i className={`status-${m.status}`}>{label(m.status)}</i></button>)}</div></section>
    <section className="completion-card"><div><h2>Review checklist</h2>{Object.entries(run.checklist).map(([k,v])=><p key={k} className={v?"checked":""}>{v?<Check size={14}/>:<CircleAlert size={14}/>} {label(k)}</p>)}</div><button disabled={busy||(!readonly&&Object.values(run.checklist).some(v=>!v))} onClick={()=>mutate(()=>reconciliationAction(run.id,readonly?"reopen":"complete"))}>{readonly?<><RefreshCw size={14}/>Explicitly reopen</>:"Complete reconciliation"}</button></section>
  </main>{selected&&<aside className="match-drawer" aria-label="Transaction details"><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><p>MATCH EVIDENCE</p><h2>{money(selected.amount)}</h2><dl><dt>Bank row</dt><dd>{selected.bank_row??"—"}</dd><dt>Ledger row</dt><dd>{selected.ledger_row??"—"}</dd><dt>Score</dt><dd>{Math.round(selected.score*100)}%</dd><dt>Rule</dt><dd>{selected.rule}</dd><dt>Review status</dt><dd>{label(selected.status)}</dd>{selected.exception_type&&<><dt>Possible exception</dt><dd>{label(selected.exception_type)}</dd></>}</dl><pre>{JSON.stringify(selected.evidence,null,2)}</pre><label>Review note<textarea disabled={readonly} value={note} onChange={e=>setNote(e.target.value)} placeholder="Add context for the audit trail"/></label><div className="drawer-actions"><button disabled={readonly||busy} onClick={()=>mutate(()=>reviewReconciliationMatch(run.id,selected.id,"rejected",note))}>Reject</button><button disabled={readonly||busy} onClick={()=>mutate(()=>reviewReconciliationMatch(run.id,selected.id,"approved",note))}>Approve</button>{selected.status!=="pending"&&<button disabled={readonly||busy} onClick={()=>mutate(()=>unmatchReconciliation(run.id,selected.id,note))}>Unmatch</button>}</div>{selected.match_type==="unmatched"&&<ManualForm match={selected} matches={run.matches} disabled={readonly||busy} onMatch={(b,l)=>mutate(()=>manualReconciliationMatch(run.id,b,l,note))}/>}</aside>}</div>;
}

function ManualForm({match,matches,disabled,onMatch}:{match:ReconciliationMatch;matches:ReconciliationMatch[];disabled:boolean;onMatch:(b:number,l:number)=>void}) { const [row,setRow]=useState(""); const bank=match.bank_row; const ledger=match.ledger_row; const options=matches.filter(m=>bank?m.ledger_row:m.bank_row); return <div className="manual-match"><h3>Manual match</h3><select value={row} onChange={e=>setRow(e.target.value)}><option value="">Select counterpart row</option>{options.map(m=><option key={m.id} value={bank?m.ledger_row??"":m.bank_row??""}>{bank?"Ledger":"Bank"} row {bank?m.ledger_row:m.bank_row}</option>)}</select><button disabled={disabled||!row} onClick={()=>onMatch(bank??Number(row),ledger??Number(row))}>Match transactions</button></div> }
